package.json

Add request as a dependency

---

README.md
api.md

fix: doc updates

---

.eslintrc.json
package.json
src/context.js
src/token-helper.js
test/context.test.js
test/ims-plugins/badImsPlugin.js
test/ims-plugins/imsPlugin.js
test/ims-plugins/incompleteImsPlugin.js
test/ims.test.js
test/index.test.js
test/token-helper.test.js

support for ims-cli plugin in aio-lib-core-ims-oauth lib

---

README.md

documentation for different config types

---

.gitignore
package.json
src/config/action.js
src/ims.js
test/ims.test.js

- first commit: fixes corner case where invalidation was not properly deleting tokens in aio lib state for the action context
- second commit: provide a validate token function on the IMS object

Add validate endpoint and fix deletion of state tokens on invalidation

---

src/config/action.js
src/config/config.js
src/index.js

jsdoc warning fixes
npm install
npm test

fix: jsdoc warnings

---

src/ims.js
test/ims.test.js

client id can be extracted from the token itself

validate ims token without specifying the client id

---

src/ims.js
test/ims.test.js

handle bad token payload on validation

---

package.json

chore(package): update @adobe/aio-lib-ims-oauth to v2.1.0

---

src/context.js
test/context.test.js

Fix setCli global

---

api.md
src/context.js
test/context.test.js

fix: setCli was clobbering existing data, instead of merging the data

---

src/ims.js
test/ims.test.js

ims.getOrganizations

---

README.md

fix: remove ims plugins in example config

---

src/token-helper.js
test/token.helper.webpack.test.js

Fixes #55 
This fixes the issue with deployed actions using ims lib failing when executed.
Related PR - [https://github.com/adobe/aio-lib-runtime/pull/8](https://github.com/adobe/aio-lib-runtime/pull/8)
Build scripts in https://github.com/adobe/aio-lib-runtime will set the global flag WEBPACK_ACTION_BUILD in case of action builds. For such build, ims lib will not include oauth and cli modules. 
unit tests and manual tests
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

Use dynamic module imports based on flag set by web pack build.

---

README.md
api.md
src/ctx/Context.js
src/index.js

fix documentation confusion for context.set with local=true in runtime action

---

README.md
test/token-helper.test.js
test/token.helper.webpack.test.js

See https://github.com/adobe/aio-lib-ims/issues/63
npm test

fix: remove unused tech_account_email

---

src/token-helper.js
test/token-helper.test.js
test/token.helper.webpack.test.js

Depends on https://github.com/adobe/aio-lib-ims-jwt/pull/25
Depends on https://github.com/adobe/aio-lib-ims-oauth/pull/30
Fixes #69 
npm test

fix: ACNA-1147 - better error message for context token generation

---

src/index.js
src/token-helper.js
test/index.test.js

Fixes #68 
Related: https://github.com/adobe/aio-lib-ims-oauth/pull/31
npm test

fix: remove unused force parameter in getToken

---

package.json

chore(package): update @adobe/aio-lib-ims-oauth to 3.2.1

---

package.json
src/ctx/ConfigCliContext.js
src/ctx/Context.js
src/ctx/StateActionContext.js
src/errors.js
src/ims.js
src/token-helper.js
test/ctx/StateActionContext.test.js
test/ims.test.js
test/token-helper.test.js
test/token.helper.webpack.test.js

Remove all direct creation of `Error` objects in favor of staticlly defined errors using `@adobe/aio-lib-core-errors`
Fixes #79 
Ensures that consumers of this library can properly differentiate errors.
Unit tests

feat(errors): use @adobe/ims-lib-core-errors for errors. fixes #79

---

.github/workflows/node.js.yml
.github/workflows/on-push-publish-to-npm.yml
.github/workflows/version-bump-publish.yml
package.json

https://github.com/adobe/aio-lib-ims-jwt/pull/30
https://github.com/adobe/aio-lib-ims-oauth/pull/39

fix: require node 12 or greater

---

package.json
src/ims.js
test/ims.test.js
test/jest.setup.js
test/token-helper.test.js
test/token.helper.webpack.test.js

feat: add proxy support

---

src/index.js
src/token-helper.js
test/index.test.js
test/token-helper.test.js

Pass options from `getToken` through to `imsLogin`
#90 
Enables browser selection
Unit tests

feat: support passing options to imsLogin. fixes #90

---

package.json

fix: remove unused @azure/identity (is actual @azure/cosmos@3.17.0 issue fixed in @adobe/aio-lib-state@2.0.1)

---

README.md

Closes #132 
Markdown preview.

fix: ACNA-2371 - OAuth Server-to-Server incorrect parameter documentation
